xx

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -16,6 +16,40 @@ on:
       - "**/README.md"
 
 jobs:
+  check:
+     if: github.event.pull_request.draft == false
+     runs-on: ubuntu-latest
+     steps:
+     - name: Install Go
+       uses: actions/setup-go@v2
+       with:
+         go-version: 1.23.x
+     - name: Checkout code
+       uses: actions/checkout@v2
+     - name: Lint
+       run: |
+         rm -rf $HOME/.cache/golangci-lint
+         make lint
+  goimports-lint:
+    if: github.event.pull_request.draft == false
+    runs-on: ubuntu-latest
+    steps:
+      - name: Install Go
+        uses: actions/setup-go@v2
+        with:
+          go-version: 1.23.x
+      - name: Checkout code
+        uses: actions/checkout@v2
+      - name: Install goimports
+        run: go install golang.org/x/tools/cmd/goimports@latest
+      - run: goimports -local . -w .
+      - run: go mod tidy
+      # If there are any diffs from goimports or go mod tidy, fail.
+      - name: Verify no changes from goimports and go mod tidy
+        run: |
+          if [ -n "$(git status --porcelain)" ]; then
+            exit 1
+          fi
   test:
     if: github.event.pull_request.draft == false
     runs-on: ubuntu-latest
